<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="ButtonNO" Id="{593d0c36-a778-4d44-b389-505244cedeb5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ButtonNO
VAR
	input AT %I* : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IsPressed" Id="{9d839024-b65a-4ac9-af8e-8dd66e30aabb}">
      <Declaration><![CDATA[PROPERTY IsPressed : BOOL]]></Declaration>
      <Get Name="Get" Id="{c882a1d8-fd95-4f7c-9833-b6b07ceec2d0}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IsPressed := input;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="IsReleased" Id="{0b008a41-96ec-4b7e-84e4-d431771c7175}">
      <Declaration><![CDATA[PROPERTY IsReleased : BOOL]]></Declaration>
      <Get Name="Get" Id="{adcd4b1c-2ed5-4aa7-9f23-40d8650a980a}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IsReleased := NOT input;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>