<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="ButtonNO" Id="{b503bddc-38ca-4d62-8359-601e5b924133}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ButtonNO EXTENDS Button
VAR
	input AT %I* : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IsPressed" Id="{57f57dcd-341b-4652-a81c-264299f27931}">
      <Declaration><![CDATA[PROPERTY IsPressed : BOOL]]></Declaration>
      <Get Name="Get" Id="{268cd101-e03e-49a7-a012-5ca5da513eca}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IsPressed := input;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="IsReleased" Id="{8562a8f3-f686-4bc7-a4b1-85d9c6e8ecfc}">
      <Declaration><![CDATA[PROPERTY IsReleased : BOOL]]></Declaration>
      <Get Name="Get" Id="{c2677609-7d27-4eda-a2da-87b7ae7910de}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IsReleased := NOT input;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>