<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="ButtonNC" Id="{3e3211aa-f658-4283-830b-d1464a00a171}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ButtonNC EXTENDS Button
VAR
	input AT %I* : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IsPressed" Id="{8ca30260-2150-4264-8ab6-f1ec95f60bc3}">
      <Declaration><![CDATA[PROPERTY IsPressed : BOOL]]></Declaration>
      <Get Name="Get" Id="{b9e1107d-adf6-4b28-a350-8cb0ca0076fb}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IsPressed := NOT input;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="IsReleased" Id="{009371a7-3770-477f-ad31-4edbccc7be49}">
      <Declaration><![CDATA[PROPERTY IsReleased : BOOL]]></Declaration>
      <Get Name="Get" Id="{41573aa6-e79b-4204-89cf-62dae66aac19}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IsReleased := input;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>